# Generated by Django 6.0.1 on 2026-03-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_login2'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
